Binarization: A numerical value is converted into a binary value (0,1)
used in image processing.
to convert coloured images to black and white.

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [8]:
df= pd.read_csv('train.csv',usecols=['Age','Fare','SibSp','Parch','Survived'])

In [9]:
df['Family']=df['SibSp']+df['Parch']

In [10]:
df

     Survived   Age  SibSp  Parch     Fare  Family
0           0  22.0      1      0   7.2500       1
1           1  38.0      1      0  71.2833       1
2           1  26.0      0      0   7.9250       0
3           1  35.0      1      0  53.1000       1
4           0  35.0      0      0   8.0500       0
..        ...   ...    ...    ...      ...     ...
886         0  27.0      0      0  13.0000       0
887         1  19.0      0      0  30.0000       0
888         0   NaN      1      2  23.4500       3
889         1  26.0      0      0  30.0000       0
890         0  32.0      0      0   7.7500       0

[891 rows x 6 columns]

In [13]:
df.drop(columns=['SibSp','Parch'])

     Survived   Age     Fare  Family
0           0  22.0   7.2500       1
1           1  38.0  71.2833       1
2           1  26.0   7.9250       0
3           1  35.0  53.1000       1
4           0  35.0   8.0500       0
..        ...   ...      ...     ...
886         0  27.0  13.0000       0
887         1  19.0  30.0000       0
888         0   NaN  23.4500       3
889         1  26.0  30.0000       0
890         0  32.0   7.7500       0

[891 rows x 4 columns]

In [14]:
df.dropna(inplace=True)

In [53]:
# with binarization
x_train,x_test,y_train,y_test=train_test_split(df[['Age','Fare','Family']],df['Survived'],test_size=0.2,random_state=42)

In [54]:
from sklearn.preprocessing import Binarizer

In [55]:
# we need to find if person is travelling with a family or not
from sklearn.compose import ColumnTransformer

In [56]:
trf=ColumnTransformer(transformers=[
    ('trf1',Binarizer(copy=False),['Family'])],
                       remainder='passthrough')

In [57]:
x_train_tf=trf.fit_transform(x_train)
x_test_tf=trf.transform(x_test)

In [58]:
x_train_tf

array([[  1.    ,  31.    ,  20.525 ],
       [  1.    ,  26.    ,  14.4542],
       [  1.    ,  30.    ,  16.1   ],
       ...,
       [  0.    ,  41.    , 134.5   ],
       [  1.    ,  33.    ,  20.525 ],
       [  0.    ,  33.    ,   7.8958]], shape=(571, 3))

In [59]:
x_train_tf=pd.DataFrame(x_train_tf,columns=['family','Age','Fare'])

In [60]:
x_train_tf

     family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [61]:
from sklearn.tree import DecisionTreeClassifier

In [62]:
clf=DecisionTreeClassifier()

In [63]:
clf.fit(x_train_tf,y_train)
y_pred=clf.predict(x_test_tf)

C:\Users\Dell\Downloads\anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [64]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6013986013986014